eind: pipeline
type: docker
name: susy-web


pipeline:
  publish-node:
    image: plugins/docker
    dockerfile: ./Dockerfile.node
    context: .
    repo: susyone/susy
    tags: ["latest", "validatorv2"]
    secrets: [docker_username,docker_password]
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - feature/drone

  publish-client:
    image: plugins/docker
    dockerfile: ./Dockerfile.client
    context: .
    repo: susyone/susyclient
    tags: ["latest", "validatorv2"]
    secrets: [docker_username,docker_password]
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - feature/drone

  publish-client:
    image: plugins/docker
    dockerfile: ./Dockerfile.proto
    context: .
    repo: susyone/susyproto
    tags: ["latest", "validatorv2"]
    secrets: [docker_username,docker_password]
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - feature/drone
